apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kasaya.fullname" . }}-backend
  labels:
    {{- include "kasaya.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.backend.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
