{{- if not .Values.secret.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kasaya.fullname" . }}
  labels:
    {{- include "kasaya.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secret.jwtSecretKey }}
  jwt-secret-key: {{ .Values.secret.jwtSecretKey | b64enc | quote }}
  {{- else }}
  jwt-secret-key: {{ randAlphaNum 64 | b64enc | quote }}
  {{- end }}
---
{{- end }}
{{- if and .Values.postgresql.enabled (not .Values.postgresql.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kasaya.fullname" . }}-postgresql
  labels:
    {{- include "kasaya.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.postgresql.auth.password }}
  postgresql-password: {{ .Values.postgresql.auth.password | b64enc | quote }}
  {{- else }}
  postgresql-password: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
---
{{- end }}
{{- if and .Values.redis.enabled (not .Values.redis.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kasaya.fullname" . }}-redis
  labels:
    {{- include "kasaya.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.redis.auth.password }}
  redis-password: {{ .Values.redis.auth.password | b64enc | quote }}
  {{- else }}
  redis-password: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
{{- end }}
