auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096

common:
  instance_addr: 127.0.0.1
  path_prefix: /tmp/loki
  storage:
    filesystem:
      chunks_directory: /tmp/loki/chunks
      rules_directory: /tmp/loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2024-01-01
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

ruler:
  enable_api: true
  rule_path: /tmp/loki/rules-temp
  storage:
    type: local
    local:
      directory: /etc/loki/rules
  alertmanager_url: http://alertmanager:9093
  remote_write:
    enabled: false

limits_config:
  # 允许无序日志（容器重启可能导致时间戳乱序）
  allow_structured_metadata: true
  volume_enabled: true
