{{- if .Values.backend.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "ckyclaw.fullname" . }}-backend
  labels:
    {{- include "ckyclaw.labels" . | nindent 4 }}
    {{- include "ckyclaw.backend.selectorLabels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.backend.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "ckyclaw.backend.selectorLabels" . | nindent 6 }}
{{- end }}
---
{{- if .Values.frontend.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "ckyclaw.fullname" . }}-frontend
  labels:
    {{- include "ckyclaw.labels" . | nindent 4 }}
    {{- include "ckyclaw.frontend.selectorLabels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.frontend.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "ckyclaw.frontend.selectorLabels" . | nindent 6 }}
{{- end }}
